### ISSUE TITLE
Python Code Problems ReadMe needs code-fences

### ISSUE THREAD

**Issue by HighnessAtharva** [learning-zone/python-interview-questions#7]
Formatting for the code solutions can be improved by adding code fences to the solution and making it more readable. I can do it if permitted.  PEP-8 styling can also be added..

Currently the solutions are raw text. 
They need to be `in a code fence for better readability.`

**Comment by learning-zone** [comment]
Hi @HighnessAtharva

Thanks for the suggestion. 
Please create a PR for the same.
